export const TYPES = {
    ALERT_ACTION: 'ALERT_ACTION',
    APPS: 'APPS',
    DASHBOARDS: 'DASHBOARDS',
    SAVED_SERACHES: 'SAVED_SERACHES',
    LOOKUPS: 'LOOKUPS',
    FIELDS: 'FIELDS',
    INDEXES: 'INDEXES',
    SOURCETYPES:'SOURCETYPES'
}